title: ApexNode Docs
description: The documenation for ApexNode.host services.
theme: just-the-docs

gems:
  - just-the-docs

url: https://docs.apexnode.host
logo: apexnode_logo_full.png
favicon: favicon.ico

aux_links:
  "Our Website": https://apexnode.host
  "Game Panel": https://panel.apexnode.host
  "Client Dashboard": https://dash.apexnode.host/dashboard
  "Join our Discord": https://apexnode.host/discord

aux_links_new_tab: true
color_scheme: dark
back_to_top: true
back_to_top_text: Back to top

callouts:
  warning:
    title: warning
    color: yellow
  danger:
    title: danger
    color: red
  success:
    title: info
    color: green
