title: ApexNode Docs
description: The documenation for ApexNode.host services.
theme: just-the-docs

permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap
  - just-the-docs

url: https://docs.apexnode.host
logo: apexnode_logo_full.png
favicon: favicon.ico

aux_links:
  "Our Website": https://apexnode.host
  "Game Panel": https://panel.apexnode.host
  "Client Dashboard": https://dash.apexnode.host/dashboard
  "Join our Discord": https://apexnode.host/discord

# Enable or disable heading anchors
heading_anchors: true
# Show navigation error report
nav_error_report: true # default is false/nil.

liquid:
  error_mode: strict
  strict_filters: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase
color_scheme: dark
back_to_top: true
back_to_top_text: Back to top

callouts:
  warning:
    title: warning
    color: yellow
  danger:
    title: danger
    color: red
  success:
    title: info
    color: green

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ["import"] # https://github.com/just-the-docs/just-the-docs/issues/1607

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # theme test code
  - fixtures/
  - spec/
  - tmp
  - .rspec
